TRI_LAYER_ENABLE = no
OLED_ENABLE = yes
GBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
TAP_DANCE_ENABLE = yes
OS_DETECTION_ENABLE = yes
MOUSEKEY_ENABLE = yes
LTO_ENABLE = yes
MUSIC_ENABLE = no

SEND_STRING_ENABLE = no
